### ISSUE TITLE
[Feature request] Support host and port parameters

### ISSUE THREAD

**Issue by aledeg** [ddelnano/dredd-hooks-php#18]
At the moment, I cannot change my dredd configuration to listen to a different host or port other than the default defined by dredd.
It would be nice to be able to change that while starting the hooks. This way, the dredd configuration could look like:

``` yaml
# dredd.yml
...
language: "bin/dredd-hooks-php --host 0.0.0.0 --port 12345"
...
hooks-worker-handler-host: 0.0.0.0
hooks-worker-handler-port: 12345
...
```
