### ISSUE TITLE
Error connecting to the hook handler. Is the handler running?

### ISSUE THREAD

**Issue by icambridge** [ddelnano/dredd-hooks-php#3]
I get the following on travis.

```
$ node_modules/dredd/bin/dredd
Configuration dredd.yml found, ignoring other arguments.
Starting server with command: app/api_v6/console server:run --docroot=web 127.0.0.1:8081
Waiting 3 seconds for server command to start...
info: Beginning Dredd testing...
Spawning `bin/dredd-hooks-php` hooks handler
Error connecting to the hook handler. Is the handler running?
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

I have no idea why, I've ensured that the file is there and executable. So I've ran the script by itself and put it into the background. This just resulted in getting socket errors when the other tests were running.

**Comment by ddelnano** [comment]
When you say "running on travis" do you mean your project that is using dredd to test your web service or are you talking about my repository running on travis?

Please post your travis.yml if its your project.  I think I can tell what the issue is from that output but I just want to verify.

Edit: Added information

**Comment by icambridge** [comment]
My project running on travis using dredd.

```
language: php
php:
  - 5.5
env:
    global:
         - ELASTICSEARCH_VERSION="1.7.1"
         - ELASTICSEARCH_EXTENSION_VERSION="3.0.0"
         - FRONTEND_PUBLIC_DIR=$TRAVIS_BUILD_DIR/src/Foodpanda/Bundle/Shop/SiteBundle/Resources/public
         - COUNTRY_CODE=va
         - PLATFORM=foodpanda

before_install:
    # php redis config
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

    # symfony config
    - cd $TRAVIS_BUILD_DIR && rm -Rf app/core/config/countries_parameters/*
    - cd $TRAVIS_BUILD_DIR && cp app/core/config/parameters_test.yml app/core/config/countries_parameters/foodpanda_va.yml

    # elastic search
    - wget --no-check-certificate https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ELASTICSEARCH_VERSION.deb
    - sudo dpkg -i --force-confnew elasticsearch-$ELASTICSEARCH_VERSION.deb
    - rm elasticsearch-$ELASTICSEARCH_VERSION.deb

    # elasticsearch plugin
    - sudo /usr/share/elasticsearch/bin/plugin -v --url http://repo.foodpanda.com/foodpanda-extension-$ELASTICSEARCH_EXTENSION_VERSION.jar --install foodpanda-extension
    - sudo service elasticsearch start

    # MySQL 5.6
    - sudo apt-get remove --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
    - sudo apt-get autoremove
    - sudo apt-get autoclean
    - sudo apt-add-repository ppa:ondrej/mysql-5.6 -y
    - sudo apt-get update
    - sudo apt-get install mysql-server-5.6 mysql-client-5.6
    - mysql -uroot -e "SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION"

install:
  - 'cd $TRAVIS_BUILD_DIR && composer self-update'
  - 'cd $TRAVIS_BUILD_DIR && composer install --no-interaction --optimize-autoloader'
  - 'cd $TRAVIS_BUILD_DIR && rm -Rf app/core/cache/*'
  - 'cd $TRAVIS_BUILD_DIR && rm -Rf app/core/logs/*'
  - 'cd $TRAVIS_BUILD_DIR && chmod -R 777 app'
  - 'cd $TRAVIS_BUILD_DIR && chmod -R 777 bin/dredd-hooks-php'
  - 'cd $TRAVIS_BUILD_DIR && php app/console assets:install web --env=test'
script:
  - AUTO_DROP_DB=1 bin/phpunit -c app/api
  - AUTO_DROP_DB=1 bin/phpunit -c app/core
  - AUTO_DROP_DB=1 bin/phpunit -c app/shop
  - AUTO_DROP_DB=1 bin/phpunit -c app/internal
  - bin/behat -p cart --suite=cart_suite --format progress -n --strict
  - AUTO_DROP_DB=1 bin/behat --profile=integration --suite=integrationApi --format progress -n --strict
  - bin/phpspec run
  - AUTO_DROP_DB=1 bin/behat --profile=api_v6 --format progress -n --strict
  - node_modules/dredd/bin/dredd
cache:
  apt: true
  directories:
    - $HOME/.composer
#    - node_modules
services:
  - redis-server
before_deploy:
  - $TRAVIS_BUILD_DIR/build-tools/create-artifact-archive -o $TRAVIS_BUILD_DIR/build-tools/build.tar.gz -b $TRAVIS_BRANCH -c $TRAVIS_COMMIT
deploy:
  provider: releases
  api-key: 9
  file: $TRAVIS_BUILD_DIR/build-tools/build.tar.gz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
```

and dredd.yml

```
dry-run: null
hookfiles: 'hooks/hooks.global.php'
language: 'bin/dredd-hooks-php'
sandbox: false
server: 'app/api_v6/console server:run --docroot=web 127.0.0.1:8081'
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: cli
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: apiary.apib
endpoint: 'http://127.0.0.1:8081/app_dev_api_v6.php/'
```
